
services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  ingestion:
    build: ./ingestion
    container_name: ecommerce_ingestion
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: sleep infinity

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7
    container_name: ecommerce_dbt
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    command: sleep infinity

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL__ALCHEMY__CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE_SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: scheduler

  flyway:
    image: flyway/flyway:10
    container_name: ecommerce_flyway
    depends_on:
      postgres:
        condition: service_healthy
    command: migrate
    volumes:
      - ./infra/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: